# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

## fake this initial migration on production server

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('student',),
                'db_table': 'connection',
            },
        ),
        migrations.CreateModel(
            name='frequently_asked_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('displayOrder', models.IntegerField()),
                ('text', models.TextField(max_length=2000, verbose_name='HTML text')),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['displayOrder'],
                'verbose_name': 'Frequently Asked Question',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('yearOfPhD', models.IntegerField(blank=True, max_length=4, null=True)),
                ('URL_for_detail', models.CharField(max_length=200, null=True)),
                ('featureImage', models.FileField(blank=True, max_length=255, null=True, upload_to='people/images/')),
                ('featureBlurb', models.TextField(blank=True, help_text='formatted with with <\\p> tags', max_length=2000, null=True)),
                ('isFeatured', models.NullBooleanField()),
                ('dateFeatured', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['lastName'],
                'db_table': 'person',
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicPhylogeny.school'),
        ),
        migrations.AddField(
            model_name='person',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='academicPhylogeny.specialization'),
        ),
        migrations.AddField(
            model_name='connection',
            name='advisor',
            field=models.ManyToManyField(related_name='_connection_advisor_+', to='academicPhylogeny.person'),
        ),
        migrations.AddField(
            model_name='connection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicPhylogeny.person'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('firstName', 'lastName')]),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('student',)]),
        ),
    ]
