# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicPhylogeny', '0002_auto_20170519_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phd',
            name='URL_for_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
