# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 00:38
from __future__ import unicode_literals

from django.db import migrations

def validateAllCurrentPhDs(apps,schema_editor):
    PhDModel = apps.get_model("academicPhylogeny", "PhD")
    for each in PhDModel.objects.all():
        each.validated = True
        each.save()

class Migration(migrations.Migration):

    dependencies = [
        ('academicPhylogeny', '0007_add_advisors_to_PhD'),
    ]

    operations = [
        migrations.RunPython(validateAllCurrentPhDs)
    ]
