# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academicPhylogeny', '0009_delete_an_FAQ'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestedPhDTextUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('firstName', 'firstName'), ('lastName', 'lastName'), ('year', 'year')], max_length=100)),
                ('value', models.TextField()),
                ('moderator_approved', models.BooleanField(default=False)),
                ('PhD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicPhylogeny.PhD')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
