# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 22:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academicPhylogeny', '0010_suggestedphdtextupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhDupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_approved', models.BooleanField(default=False)),
                ('suggested_update_fixture', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.CreateModel(
        #     name='userContact',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('email', models.EmailField(max_length=254, verbose_name='Your Email Address')),
        #         ('first_name', models.CharField(max_length=100, verbose_name='Your First Name')),
        #         ('last_name', models.CharField(max_length=100, verbose_name='Your Last Name')),
        #         ('affiliation', models.CharField(max_length=100, verbose_name='Your Institutional Affiliation')),
        #         ('message', models.TextField(max_length=2000, verbose_name='Your message')),
        #         ('dealt_with', models.BooleanField(default=False)),
        #         ('admin_notes', models.TextField(max_length=1000)),
        #         ('date_sent', models.DateTimeField(auto_now_add=True)),
        #         ('date_last_modified', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'ordering': ('dealt_with', '-date_sent'),
        #     },
        # ),
        migrations.AlterModelOptions(
            name='phd',
            options={'ordering': ['lastName'], 'verbose_name': 'PhD', 'verbose_name_plural': 'PhDs'},
        ),
        migrations.AlterField(
            model_name='phd',
            name='firstName',
            field=models.CharField(max_length=100, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='phd',
            name='lastName',
            field=models.CharField(max_length=100, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='phd',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Year PhD Awarded'),
        ),
        migrations.AlterField(
            model_name='suggestedphdtextupdate',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestedphdtextupdate',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
