# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicPhylogeny', '0011_auto_20170616_2222'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='userContact',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('email', models.EmailField(max_length=254, verbose_name='Your Email Address')),
        #         ('first_name', models.CharField(max_length=100, verbose_name='Your First Name')),
        #         ('last_name', models.CharField(max_length=100, verbose_name='Your Last Name')),
        #         ('affiliation', models.CharField(max_length=100, verbose_name='Your Institutional Affiliation')),
        #         ('message', models.TextField(max_length=2000, verbose_name='Your message')),
        #         ('dealt_with', models.BooleanField(default=False)),
        #         ('admin_notes', models.TextField(max_length=1000)),
        #         ('date_sent', models.DateTimeField(auto_now_add=True)),
        #         ('date_last_modified', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'ordering': ('dealt_with', '-date_sent'),
        #     },
        # ),
        migrations.AlterModelOptions(
            name='phdupdate',
            options={'verbose_name': 'Suggested Update', 'verbose_name_plural': 'Suggested Updates'},
        ),
        migrations.AddField(
            model_name='phd',
            name='source_of_info',
            field=models.CharField(default='in db version 1.0', max_length=300, verbose_name="What's the source of this info?"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phd',
            name='submitter_email',
            field=models.EmailField(default='preexisted@dbversion1.com', max_length=254, verbose_name='Your Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phdupdate',
            name='source_of_info',
            field=models.CharField(default='preexisted in database version 1.0', max_length=300, verbose_name="What's the source of this info?"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phdupdate',
            name='submitter_email',
            field=models.EmailField(default='preexisted@dbversion1.com', max_length=254, verbose_name='Your Email Address'),
            preserve_default=False,
        ),
    ]
