# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 11:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academicPhylogeny', '0012_auto_20170617_2222'),
    ]

    operations = [

        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.CharField(blank=True, max_length=100, null=True)),
                ('current_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('reputation_points', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='associated_PhD',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academicPhylogeny.PhD'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
