# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academicPhylogeny', '0013_auto_20170619_1153'),
    ]

    operations = [

        migrations.AddField(
            model_name='userprofile',
            name='moderator_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_blurb',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Describe your research program'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='research_website',
            field=models.URLField(blank=True, null=True),
        ),

    ]
