# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicPhylogeny', '0014_auto_20170620_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdupdate',
            name='PhD',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academicPhylogeny.PhD'),
            preserve_default=False,
        ),
    ]
