# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicPhylogeny', '0016_auto_20170629_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialMediaPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.BooleanField(default=True)),
                ('twitter', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='socialmediaposts',
            name='PhD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academicPhylogeny.PhD'),
        ),
    ]
