# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-14 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academicPhylogeny', '0021_add_legacy_picture'),
    ]

    operations = [

        migrations.AddField(
            model_name='phd',
            name='submitter_emailed_after_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phd',
            name='advisor',
            field=models.ManyToManyField(blank=True, null=True, to='academicPhylogeny.PhD'),
        ),
        migrations.AlterField(
            model_name='phd',
            name='submitter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Submitter username'),
        ),
        migrations.AlterField(
            model_name='phdupdate',
            name='submitter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter_user', to=settings.AUTH_USER_MODEL, verbose_name='Submitter username'),
        ),
    ]
